#ifndef ODRIVE_CONF_H
#define ODRIVE_CONF_H

#include "utils/math_utils.h"
#include <sdkconfig.h>

#define ODRIVE_LOGGER_TAG "ODRIVE"

// ODrive timing constants
#define ODRIVE_HEARTBEAT_TIMEOUT_MS 200
#define ODRIVE_ENCODER_ESTIMATES_TIMEOUT_MS 50
#define ODRIVE_MAX_AXIS_STATE_CHANGE_TIME_S 1
#define ODRIVE_QUEUE_ACCESS_TIMEOUT_MS 10

// ODrive CAN configuration
#define ODRIVE_CAN_DATA_LENGTH 8
#define ODRIVE_CAN_MAX_RTR_RESPONSE_TIME_MS 500
#define ODRIVE_CAN_MAX_TRANSMIT_QUEUE_TIMEOUT_MS 10
#define ODRIVE_CAN_MAX_RECEIVE_QUEUE_TIMEOUT_MS 10

// User-configurable via Kconfig
#ifdef CONFIG_ODRIVE_MAX_CALIBRATION_TIME_S
#define ODRIVE_MAX_CALIBRATION_TIME_S CONFIG_ODRIVE_MAX_CALIBRATION_TIME_S
#else
#define ODRIVE_MAX_CALIBRATION_TIME_S 20
#endif

#define ODRIVE_MAX_MESSAGE_TIMEOUT_MS MAX(ODRIVE_HEARTBEAT_TIMEOUT_MS, ODRIVE_ENCODER_ESTIMATES_TIMEOUT_MS)

#endif // ODRIVE_CONF_H